from typing import Protocol


class ProviderRuntime(Protocol):
    async def list_models(self, user_id: str) -> list[str]: ...
    async def verify_model(self, user_id: str, model: str) -> dict: ...


class ProviderHandler(Protocol):
    def validate_config(self, config: dict, auth: dict | None) -> list[dict]: ...
    async def list_models(self, user_id: str) -> list[str]: ...
    async def verify_model(self, user_id: str, model: str) -> dict: ...
