import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import type { ValidationContract, ValidationLevel } from "./model";

const empty: ValidationContract = { levels: [
  { name: "exists_parseable", message_key: "workflow.validation.exists_parseable", params_schema: { format: "auto" } },
  { name: "required_sections", message_key: "workflow.validation.required_sections", params_schema: { sections: [], heading_levels: [1, 2, 3, 4, 5, 6] } },
  { name: "content_rule", message_key: "workflow.validation.content_rule", params_schema: { rule_type: "required_terms", terms: [] } },
] };
const tokens = (value: unknown) => Array.isArray(value) ? value.join(", ") : "";
const split = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean);

export function OutputValidationDialog({ open, output, inputs, value, onOpenChange, onSave, onRemove }: { open: boolean; output: string; inputs: string[]; value?: ValidationContract; onOpenChange: (open: boolean) => void; onSave: (contract: ValidationContract) => void; onRemove: () => void }) {
  const { t } = useTranslation();
  const [levels, setLevels] = useState<ValidationLevel[]>(value?.levels ?? empty.levels);
  useEffect(() => { if (open) setLevels(value?.levels?.map((level) => ({ ...level, params_schema: { ...level.params_schema } })) ?? empty.levels.map((level) => ({ ...level, params_schema: { ...level.params_schema } }))); }, [open, value]);
  const patch = (index: number, changes: Record<string, unknown>) => setLevels((old) => old.map((level, i) => i === index ? { ...level, params_schema: { ...level.params_schema, ...changes } } : level));
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[85dvh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{t("editor.outputValidationTitle", { output })}</DialogTitle><DialogDescription>{t("editor.outputValidationDescription")}</DialogDescription></DialogHeader>
    <fieldset className="grid gap-3"><legend className="font-medium">{t("editor.syntaxParse")}</legend><label className="grid gap-1 text-sm">{t("editor.validationFormat")}<select aria-label={t("editor.validationFormat")} className="rounded-md border border-input bg-background px-3 py-2" value={String(levels[0]?.params_schema.format ?? "auto")} onChange={(e) => patch(0, { format: e.target.value })}>{["auto", "text", "json", "markdown"].map((format) => <option key={format}>{format}</option>)}</select></label></fieldset>
    <fieldset className="grid gap-3"><legend className="font-medium">{t("editor.formatStructure")}</legend><label className="grid gap-1 text-sm">{t("editor.requiredKeys")}<input className="rounded-md border border-input bg-background px-3 py-2" value={tokens(levels[1]?.params_schema.required ?? [])} onChange={(e) => patch(1, { required: split(e.target.value) })} /></label><label className="grid gap-1 text-sm">{t("editor.requiredSections")}<input className="rounded-md border border-input bg-background px-3 py-2" value={tokens(levels[1]?.params_schema.sections ?? [])} onChange={(e) => patch(1, { sections: split(e.target.value) })} /></label><label className="grid gap-1 text-sm">{t("editor.headingLevels")}<input inputMode="numeric" className="rounded-md border border-input bg-background px-3 py-2" value={tokens(levels[1]?.params_schema.heading_levels ?? [])} onChange={(e) => patch(1, { heading_levels: split(e.target.value).map(Number).filter((n) => n >= 1 && n <= 6) })} /></label></fieldset>
    <fieldset className="grid gap-3"><legend className="font-medium">{t("editor.rules")}</legend><label className="grid gap-1 text-sm">{t("editor.requiredTerms")}<input className="rounded-md border border-input bg-background px-3 py-2" value={tokens(levels[2]?.params_schema.terms ?? [])} onChange={(e) => patch(2, { terms: split(e.target.value) })} /></label><label className="grid gap-1 text-sm">{t("editor.validationRule")}<select className="rounded-md border border-input bg-background px-3 py-2" value={String(levels[2]?.params_schema.rule_type ?? "required_terms")} onChange={(e) => patch(2, { rule_type: e.target.value })}><option value="required_terms">{t("editor.requiredTerms")}</option><option value="supported_claims">{t("editor.supportedClaims")}</option></select></label>{levels[2]?.params_schema.rule_type === "supported_claims" && <label className="grid gap-1 text-sm">{t("editor.inputArtifact")}<select className="rounded-md border border-input bg-background px-3 py-2" value={String(levels[2]?.params_schema.input_artifact ?? "")} onChange={(e) => patch(2, { input_artifact: e.target.value })}><option value="" />{inputs.map((input) => <option key={input}>{input}</option>)}</select></label>}</fieldset>
    <DialogFooter className="flex-wrap sm:flex-row sm:justify-between"><Button type="button" variant="outline" onClick={onRemove}>{t("editor.removeValidation")}</Button><Button type="button" onClick={() => { onSave({ levels }); onOpenChange(false); }}>{t("editor.saveValidation")}</Button></DialogFooter></DialogContent></Dialog>;
}
